## CREDENCIALES PARA MARIADB
MARIADB_USER="root"
MARIADB_PASSWORD="d4t0s4b1ert0s"
MARIADB_HOST="127.0.0.1"
MARIADB_DB="MDA"

# MARIADB_USER="quantomm_dev"
# MARIADB_PASSWORD="quantomm_dev"
# MARIADB_HOST="172.17.0.2"
# MARIADB_DB="socrata"
